IF NOT EXISTS (SELECT * FROM SYSOBJECTS WHERE NAME = 'NOTICE')
BEGIN
    CREATE TABLE NOTICE (
        ID UNIQUEIDENTIFIER PRIMARY KEY,
        TITLE VARCHAR(255) NOT NULL,
        CONTENT VARCHAR(255) NOT NULL,
        AUTHOR_ID UNIQUEIDENTIFIER,
        START_DATE DATETIME2,
        END_DATE DATETIME2,
        CREATED_DATE DATETIME2,
        TOTAL_VIEW INT DEFAULT 0,
        MODIFIED_DATE DATETIME2,
        MODIFIED_BY VARCHAR(255)
    );
END;
GO

IF NOT EXISTS (SELECT * FROM SYSOBJECTS WHERE NAME = 'ATTACHMENTS')
BEGIN
    CREATE TABLE ATTACHMENTS (
        ID UNIQUEIDENTIFIER PRIMARY KEY,
        FILE_NAME VARCHAR(255) NOT NULL,
        FILE_TYPE VARCHAR(255) NOT NULL,
        FILE_CONTENT VARBINARY(MAX) NOT NULL,
        CREATED_DATE DATETIME2,
        MODIFIED_DATE DATETIME2,
        MODIFIED_BY VARCHAR(255),
        NOTICE_ID UNIQUEIDENTIFIER
    );
END;
GO

IF NOT EXISTS (SELECT * FROM SYSOBJECTS WHERE NAME = 'USER_MANAGEMENT')
BEGIN
    CREATE TABLE USER_MANAGEMENT (
        ID UNIQUEIDENTIFIER PRIMARY KEY,
        USERNAME VARCHAR(255) NOT NULL,
        PASSWORD VARCHAR(255) NOT NULL,
        ROLE VARCHAR(255) NOT NULL,
        CREATED_DATE DATETIME2,
        MODIFIED_DATE DATETIME2,
        MODIFIED_BY VARCHAR(255)
    );
END;
GO

